# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3478524d4970470775f930bd73d8184e2cb39703d1822c6d7f91f01ee54a84c361b454153a9311bafe3e31831c4e547687e8ee7528291107e8497aa8214d46c4

test:
  secret_key_base: e1109ead06dfbc94ddf8b65fb9d56d041c269cebca607e87eed85e89da88e47824093e82083ba816ceb681296efe29ed57a764448a7244eb6936f55f1355ecb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
